# update-vmtools-smb.yml

---
- hosts: windows
  tasks:
  - name: Install VMware Tools (from network share)
    win_package:
      path: \\server\share\setup64.exe
      arguments: /s /v "/qn REBOOT=R" /l C:\Temp\VMwareToolsInstall.log
      state: present
    become: true
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    
    vars:
      ansible_become_user: "{{ ansible_become_user }}"
      ansible_become_pass: "{{ ansible_become_pass }}"
