# update-vmtools-copy.yml

---
- hosts: windows
  tasks:
  - name: Copy File
    win_copy:
      src: \\driftar.lab\NETLOGON\vmtools\setup64.exe
      dest: c:\TEMP\
      remote_src: yes
      state: present
    become: true
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: "{{ ansible_become_user }}"
      ansible_become_pass: "{{ ansible_become_pass }}"

  - name: Install VMware Tools
    win_package:
      path: c:\TEMP\setup64.exe
      arguments: /s /v "/qn REBOOT=R" /l C:\Temp\VMwareToolsInstall.log
      state: present
